### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by edysegura** [isnack/tcc-testes-automatizados#1]
Olá @isnack!

Sugiro que você altere o nome do repositório para tcc-testes-automatizados facilitando a utilização no prompt de comando.

Também sugiro uma melhoria na descrição do projeto para algo como "Trabalho de conclusão de curso sobre testes automatizados no desenvolvimento de software".

![image](https://cloud.githubusercontent.com/assets/5324414/16715447/1d321d36-46b6-11e6-9edb-6219ef53bd13.png)

**Comment by isnack** [comment]
Alteração da descrição e nome do repositório  realizada.
